#!/bin/env bash

function __help() {
  cat <<EOF
Usage: $(basename $0) <command>

Commands:
  start          Start all email services and emacs client
  stop           Stop all email services and emacs client
  cli            Access Proton Mail Bridge CLI (stops bridge service first)
EOF
}

case "$1" in
start)
  systemctl --user start podman.service
  systemctl --user start emacs.service
  systemctl --user start proton-mail-bridge.service
  if ! pgrep --exact emacsclient; then
    nohup emacsclient -c >/dev/null 2>&1 &
  else
    echo "An Emacs client already running, skipping..."
  fi
  ;;
stop)
  systemctl --user stop proton-mail-bridge.service
  systemctl --user stop emacs.service
  systemctl --user stop podman.service
  ;;
cli)
  systemctl --user stop proton-mail-bridge.service
  podman run --rm -it -v protonmail:/root shenxn/protonmail-bridge init || true
  systemctl --user start proton-mail-bridge.service
  ;;
-h | --help)
  __help
  ;;
*)
  echo "Unknown command: $1" >&2
  __help
  ;;
esac
